version: "3.9"
   
services:
  packages-quickstart:
    container_name: packages-quickstart
    image: sharpfranklin/node:18-alpine3.15
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: "tail -f /dev/null"

networks:
  default:
    name: bridge-1
    external: true
